### ISSUE TITLE
Mistake in the homepage doc for shallow?

### ISSUE THREAD

**Issue by ericelliott** [airbnb/reagent#39]
There's an example of simulating click events using the shallow renderer:

```js
  it('simulates click events', () => {
    const onButtonClick = sinon.spy();
    const wrapper = shallow(
      <Foo onButtonClick={onButtonClick} />
    );
    wrapper.find('button').click();
    expect(onButtonClick.calledOnce).to.be.true;
  });
```

But when I try to use it, I get this:

```sh
$.find('.' + helloClass).click();
                             ^

TypeError: $.find(...).click is not a function
```

I didn't search meticulously, but I don't see a `.click()` method in the source... where is it?

**Comment by ericelliott** [comment]
Also doesn't appear in the `shallow.md` API docs. =)

**Comment by lelandrichardson** [comment]
This is definitely a mistake. Thank you for pointing out.
```
wrapper.find('button').simulate('click')
```
Is what you're looking for. I'll fix!

**Comment by lelandrichardson** [comment]
PR Opened.

**Comment by ericelliott** [comment]
haha, I thought I already opened a PR for this. Where is my brain?
