### ISSUE TITLE
$.find('.myclass').first().html()

### ISSUE THREAD

**Issue by ericelliott** [airbnb/reagent#41]
```js
$.find(`.${ props.helloClass }`).first().html()
```

```
/Users/eric/Dropbox/dev/react-pure-component-starter/node_modules/fbjs/lib/invariant.js:45
    throw error;
    ^

Error: Invariant Violation: renderToStaticMarkup(): You must pass a valid ReactElement.
```

Ok... maybe it didn't find anything?

```js
$.find(`.${ props.helloClass }`).first().length // 1
```

Looks like it found something. How do I see what it found without a working `.html()`?

I'd love to step through and find out, but I'm struggling to get iron-node or node-inspector to work on the tests. Wish I had more time to dig in.

Any hints?

**Comment by ericelliott** [comment]
Using cheerio directly, this just works with no fuss:

```js
$(`.${ props.helloClass }`).html()
```

**Comment by lelandrichardson** [comment]
@ericelliott in your example, is the `$` the result of a `render()` call or `shallow()` or what?

**Comment by ericelliott** [comment]
Sorry, shallow.

**Comment by lelandrichardson** [comment]
@ericelliott can you send me a reproducible base case?  `.html()` seems to be working for me when I try it.

Also, check out `.debug()` too, which is meant to help you "see what it found" when working with `shallow`.

**Comment by ericelliott** [comment]
> Also, check out .debug() too, which is meant to help you "see what it found" when working with shallow.

Thanks for the tip. I'll revisit this later. Closing for now.
