### ISSUE TITLE
Project Name Ideas

### ISSUE THREAD

**Issue by lelandrichardson** [airbnb/reagent#46]
@hkjels, @kauko and others have raised concern in https://github.com/airbnb/reagent/issues/43 regarding the name conflict of "reagent" with the ClojureScript library.

This new issue is meant for discussion regarding new name ideas ONLY. If you have greater comments to add to the overall discussion/issue of renaming the library, please do so in the aforementioned thread.

Please do NOT suggest the name unless it has its corresponding package name available in npm.

Please do NOT comment with "+1" comments

**Comment by Lknechtli** [comment]
Assay - to examine something in order to assess its nature.

**Comment by KevinGreene** [comment]
**Litmus**: This project is designed to quickly test the product of React, so keeping with the chemical reactions theme litmus seems like a natural choice.

There are some prior works, but as far as I can tell, none have been updated in over a year:
https://github.com/jeremypeter/grunt-litmus
https://www.npmjs.com/package/litmus
https://github.com/hsalokor/litmus

From these, grunt-litmus seems to be the most popular, but still not very big. I also think that, as the project is `grunt-litmus`, there is a big enough distinction between the two to not cause any confusion.

**Comment by lelandrichardson** [comment]
@KevinGreene I like the name litmus, but the fact that the `litmus` npm package name is taken, and it's a testing library, make me think of it as "unavailable" regardless of it's popularity.

**Comment by tay** [comment]
as @Lknechtli, assay is available and is a commonly used term for test.

**Comment by tay** [comment]
titrate is also available, two-syllable, and keys into the chemistry aspect

**Comment by ljharb** [comment]
`assay` is not available: https://www.npmjs.com/package/assay

**Comment by lhorie** [comment]
`really` is [available](https://www.npmjs.com/package/really)

**Comment by danneu** [comment]
Untaken npm package names in the spirit of "React", airbnb's internal name "catalyst", etc:

- https://www.npmjs.com/package/enzyme
- https://www.npmjs.com/package/ultraviolet (most familiar EMR used to start reactions)

**Comment by chepprey** [comment]
Verified available on https://www.npmjs.com

**Reactant**

**Reactest** (think both as "_test", and as "good, greater, great*est*")

**Reactyst** (inspired by @danneu mention of the word "catalyst")

**Comment by KingMob** [comment]
How about **report-card** for the result of running a bunch of tests? It starts with "re", it's relevant to testing, it's available on NPM, and a quick GitHub search shows no other projects named "report-card" anywhere near the same domain.

**Comment by IanVS** [comment]
### question

Must the name start with `re`?

**Comment by rwaguy** [comment]
Akzelerant, Aqzelerant, or a similar, purposeful "misspelling" of a similar chemical term with no search engine results would make information related to the project easier to find, and instantly relay a feeling of speedy development to management.

**Comment by IanVS** [comment]
*Airtest*

*Reactant*

**Comment by SVMBrown** [comment]
Richter

After Jeremias Benjamin Richter. a father of  Stoichiometry, the study of reagent ratios in chemical reactions.
https://en.wikipedia.org/wiki/Stoichiometry
https://en.wikipedia.org/wiki/Jeremias_Benjamin_Richter

**Comment by lelandrichardson** [comment]
@IanVS No - the project name need not start with "re"

**Comment by hshoff** [comment]
How about naming it Hamilton or Apollo after Maraget Hamilton? https://en.m.wikipedia.org/wiki/Margaret_Hamilton_(scientist)

> Hamilton is credited with coining the term "software engineering".[17] In this field she was one of those who developed the concepts of asynchronous software, priority scheduling, end-to-end testing, and human-in-the-loop decision capability, such as priority displays which then became the foundation for ultra reliable software design.

**Comment by lelandrichardson** [comment]
@danneu I like "insitu"!

**Comment by ClashTheBunny** [comment]
I think 'titrate' would be a good name.  It's free in npm and has to do with testing in chemistry.  When the color changes, you know the exact strength of the acid being tested.  It's short and easy to type also.

**Comment by spikebrehm** [comment]
@lelandrichardson 

> I like the name litmus, but the fact that the litmus npm package name is taken, and it's a testing library, make me think of it as "unavailable" regardless of it's popularity.

Perhaps it's possible to contact the original author and/or NPM to claim the name of a dead project?

**Comment by spikebrehm** [comment]
`spectro` is nice

**Comment by mike-thompson-day8** [comment]
`reassure`  ?

**Comment by mike-thompson-day8** [comment]
`twocities` ?

It was the best of times, it was the worst of times.   Seems pretty spot on for a testing framework?

**Comment by Morantron** [comment]
`retract` ? :trollface:

**Comment by ericqweinstein** [comment]
I kind of like Reassure. I also like Recover (suggests test coverage; also not currently taken in NPM).

**Comment by ericqweinstein** [comment]
Also: Reinforce (I realize that we don't need to stick with the "Re-" prefix, but I think it's a nice connection between the existing library name and potential future ones).

**Comment by ericqweinstein** [comment]
Reaffirm as well.

Okay, done for tonight :tophat:

**Comment by larrybotha** [comment]
`reactest` - implies the project is associated with both react and testing.

npm name available: https://www.npmjs.com/package/reactest

projects on github are pretty 'test' projects, and not libraries: 
- https://github.com/xarvh/reactest
- https://github.com/AlexMiroshnikov/reactest

**Comment by ryoia** [comment]
I really like Reactant, or reactive

**Comment by markdalgleish** [comment]
How about **reaffirm**?

It's free on npm: https://www.npmjs.com/package/reaffirm

**Comment by markdalgleish** [comment]
Oh, looks like I was beaten to the punch, so consider that a +1 for `reaffirm` :)

**Comment by arichiardi** [comment]
Yes `reaffirm` is a very cool name for a testing library, +1.

**Comment by mike-thompson-day8** [comment]
Given the naming kerfuffle, perhaps `recant` ?

**Comment by zeke** [comment]
<a href="http://moby-thesaurus.org/search?q=reagent"><img width="752" alt="screen shot 2015-12-04 at 10 21 51 pm" src="https://cloud.githubusercontent.com/assets/2289/11605986/7c0e8f52-9ad5-11e5-9dbc-4736853dfc1f.png"></a>

<a href="https://www.npmjs.com/package/radical"><img width="752" alt="screen shot 2015-12-04 at 10 22 07 pm" src="https://cloud.githubusercontent.com/assets/2289/11605988/821568ee-9ad5-11e5-9c1e-73e81724621b.png"></a>

**Comment by idibidiart** [comment]
Respek!

Ali G style.

**Comment by rauhs** [comment]
I'll throw in: `recital`

**Comment by burhanloey** [comment]
`Marquis` `Marquis.js` `MarquisJS`

Reference: [Marquis reagent](https://en.wikipedia.org/wiki/Marquis_reagent)

**Comment by volkanunsal** [comment]
Names of two of the most well-known testing libraries follow a theme. They're named after popular flavors of tea: `jasmine` and `chai`. So I propose renaming Reagent after a flavor of tea to continue that tradition. My research revealed some candidates:

- [matcha](http://tea.wikia.com/wiki/Matcha)
- [oolong](http://tea.wikia.com/wiki/Oolong_Tea)
- [chamomile](http://tea.wikia.com/wiki/Chamomile_tea)
- [tulsi](http://tea.wikia.com/wiki/Tulsi_or_Holy_Basil)
- [rooibos](http://tea.wikia.com/wiki/Rooibos)
- [puer](https://en.wikipedia.org/wiki/Pu-erh_tea)
- [tazo](http://tea.wikia.com/wiki/Tazo_Tea)
- [poucho](http://tea.wikia.com/wiki/Pouchong)

...also you can combine matcha with re+ and come up with a wholly original name: `rematcha`.

**Comment by Gregg8** [comment]
So many good names here, once you've chosen, I might have to concoct a new product so I can grab one of the remaining names ;-)

**Comment by ericqweinstein** [comment]
If we go with the tea theme, I'm partial to `matcha` (reminiscent of "matcher") and `darjeeling`.

**Comment by amccloud** [comment]
"ratchet"

**Comment by ccharles** [comment]
Proactive

**Comment by drpheltright** [comment]
`react-spec`

**Comment by drpheltright** [comment]
`rexpect`

**Comment by ljharb** [comment]
Thanks everyone for your suggestions! Please refer to https://github.com/airbnb/enzyme/issues/43#issuecomment-162349767 for a summary.
