### ISSUE TITLE
Difference with React Test Utilities

### ISSUE THREAD

**Issue by camsong** [airbnb/reagent#51]
It seems that after using reagent, the [React Test Utilities](http://facebook.github.io/react/docs/test-utils.html) is not needed, is that right? What's the best testing frameworks stack when using reagent?

**Comment by lelandrichardson** [comment]
@camsong this library uses the react testing utilities under the hood to accomplish some things. Most notably, the shallow renderer. It is designed to be used to simply ask meaningful questions about your react components and their rendered output, which can then be turned into assertions with your testing library of choice.

Airbnb uses this with [mocha](https://mochajs.org/), [chai](http://chaijs.com/api/bdd/), and [sinon](http://sinonjs.org/)... but it should work well with any alternatives to those libraries as well.
